FROM            codecov/base
MAINTAINER      Codecov <hello@codecov.io>

WORKDIR         /home

COPY            . .

COPY            dockerscripts/entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/
COPY            config/production.yml /config/codecov.yml

HEALTHCHECK     --start-period=5s --timeout=5s \
                CMD /usr/bin/healthcheck.sh

ENTRYPOINT      ["/usr/bin/entrypoint.sh"]
